#!/usr/bin/python
import sys
import os
from random import randint
import subprocess
#Change this to your wordlist:
########################################
file='/home/smokeless/flipflop/hostnames'
########################################
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def change_hostname():
    f = open( file, 'r' )
    words = f.readlines()
    f.close()
    sizeof = len(words)
    newHostName = words[randint(0,sizeof)]
    print( "Changing hostname to:", bcolors.OKGREEN, newHostName, bcolors.ENDC)
    try:
        subprocess.call( 'hostnamectl ' + 'set-hostname ' + newHostName, shell=True ) 
    except:
        e = sys.exc_info()[0]
        print( bcolors.FAIL, "Could not change hostname!!!", bcolors.ENDC )
#Maybe make this call without shell?

def change_mac():
    interfaces = os.listdir('/sys/class/net/')
    for iface in interfaces:
        if iface != "lo":
            try:
                status = subprocess.call([ 'macchanger', '-r', iface ])
                if status == 0:
                    print( bcolors.OKGREEN, "MAC randomized.", bcolors.ENDC )
                else:
                    print( bcolors.FAIL, "Could not change MAC!!!", bcolors.ENDC)
            except:
                e = sys.exc_info()[0]
                print( bcolors.FAIL, "Could not change MAC!!!", bcolors.ENDC )
        else:
            print( "Not changing loopback interface." )


change_hostname()
change_mac()
